# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8dc9bf35a56670b4ae523291346faca76d44c341ab2cbe8f4154d1fbeeb6c7e124ea7912012b928942709058dfa6777ffdef40a30c8fd146f000463de83cf0ea

test:
  secret_key_base: c5a4d9b6e3da9c0aa07658a312597981a13c55f6400ea82a9690018b07494ecd50b2a721bd3cc3bf1eb46abfa2cc68a34b76be821225d910096162954308e106

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
